---
name: github
provider: github.com
repository: docker-hadolint
url: https://github.com/cardboardci/docker-hadolint
clone:
  ssh: git@github.com:cardboardci/docker-hadolint.git
  https: https://github.com/cardboardci/docker-hadolint.git